### ISSUE TITLE
az cli extension add command fails in ubuntu agent

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/azure-pipelines-image-generation#1111]
**Describe the bug**
The below command started failing recently. This could have been caused by this recent change - https://github.com/microsoft/azure-pipelines-image-generation/commit/d6fc0cc07fea34f551492927cad1ae0fb366f041

az extension add -n application-insights

(This command was executed under az cli task)

**Exception message:**
```
Installing collected packages: application-insights

Successfully installed application-insights-0.1.1
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/az/lib/python3.6/site-packages/pip/commands/install.py", line 388, in run
    ensure_dir(options.target_dir)
  File "/opt/az/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/opt/az/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/azureExtensionDir/application-insights'

DEBUG: Command '['/opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/usr/local/lib/azureExtensionDir/application-insights', '/tmp/tmprjc1h2b3/application_insights-0.1.1-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 2.
DEBUG: Pip failed so deleting anything we might have installed at /usr/local/lib/azureExtensionDir/application-insights
ERROR: cli.azure.cli.core.util : An error occurred. Pip failed with status code 2. Use --debug for more information.
ERROR: An error occurred. Pip failed with status code 2. Use --debug for more information.
INFO: az_command_data_logger : exit code: 1
INFO: telemetry.save : Save telemetry record of length 2427 in cache
WARNING: telemetry.check : Negative: The /home/vsts/work/_temp/.azclitask/telemetry.txt was modified at 2019-07-24 23:13:48.818409, which in less than 600.000000 s
```

we were able to fix this by setting env variable AZURE_EXTENSION_DIR to ./az-extension-dir.

**Comment by gauravsaralMs** [comment]
Thanks for reporting this...
I am trying to fix this but in the meantime we will revert this.

**Comment by manishsat** [comment]
Can you add a test case to catch at build/release time.
