### ISSUE TITLE
Docker build fails with MSBuild internal failure (only on hosted agent)

### ISSUE THREAD

**Issue by joshlang** [microsoft/azure-pipelines-image-generation#1369]
See https://developercommunity.visualstudio.com/content/problem/804285/docker-msbuild-the-filename-property-should-not-be.html

Since yesterday, with no changes to our pipeline, the build started to fail.  

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.
 ---> System.ComponentModel.Win32Exception (0x80004005): The FileName property should not be a directory unless UseShellExecute is set.
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
   --- End of inner exception stack trace ---
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode(String msbuildLocation, String commandLineArgs, Int32 nodeId, INodePacketFactory factory, Int64 hostHandshake, Int64 clientHandshake, NodeContextTerminateDelegate terminateNode)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode(Int32 nodeId, INodePacketFactory factory, NodeConfiguration configuration)
   at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration)
   at Microsoft.Build.BackEnd.NodeManager.CreateNode(NodeConfiguration configuration, NodeAffinity nodeAffinity)
   at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass67_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
   at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
```

The identical dockerfile will build on my local machine without any trouble.

**Comment by joshlang** [comment]
We are being affected by:  https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1843018

I confirmed it by adding "cat /proc/1/maps" to a docker run step.

```
Step 4/12 : RUN cat /proc/1/maps
 ---> Running in 1ac203d4fc01
55e4c09e0000-55e4c09fc000 r-xp 00000000 08:01 2358542                    /
55e4c0bfb000-55e4c0bfd000 r--p 0001b000 08:01 2358542                    /
55e4c0bfd000-55e4c0bfe000 rw-p 0001d000 08:01 2358542                    /
55e4c0bfe000-55e4c0c00000 rw-p 00000000 00:00 0 
55e4c1440000-55e4c1461000 rw-p 00000000 00:00 0                          [heap]
7f1b74406000-7f1b745ed000 r-xp 00000000 08:01 4394439                    /
7f1b745ed000-7f1b747ed000 ---p 001e7000 08:01 4394439                    /
7f1b747ed000-7f1b747f1000 r--p 001e7000 08:01 4394439                    /
7f1b747f1000-7f1b747f3000 rw-p 001eb000 08:01 4394439                    /
7f1b747f3000-7f1b747f7000 rw-p 00000000 00:00 0 
7f1b747f7000-7f1b7481e000 r-xp 00000000 08:01 4394418                    /
7f1b74a18000-7f1b74a1a000 rw-p 00000000 00:00 0 
7f1b74a1e000-7f1b74a1f000 r--p 00027000 08:01 4394418                    /
7f1b74a1f000-7f1b74a20000 rw-p 00028000 08:01 4394418                    /
7f1b74a20000-7f1b74a21000 rw-p 00000000 00:00 0 
7ffe87996000-7ffe879b7000 rw-p 00000000 00:00 0                          [stack]
7ffe879c1000-7ffe879c4000 r--p 00000000 00:00 0                          [vvar]
7ffe879c4000-7ffe879c5000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

**Comment by joshlang** [comment]
https://github.com/Microsoft/azure-pipelines-image-generation/issues/506

I just ran into this.  It's obviously the change that broke things for us:  The new release of 18.04 as a supported hosted build agent

SWEET!  I'm glad to see 18.04 be released.  Gotta patch up this bug though :D  

I expect anyone would be affected if they are using a combination of:
- vmImage: ubuntu-latest
- docker build
- dotnet build/etc within docker

**Comment by farshidnz** [comment]
I am also experiencing the same issue using `ubuntu-latest` for build pipeline on Azure Devops for a .Net Core application.

My workaround was changing the agent vm image from `ubuntu-latest` to `ubuntu-16.04`.

**Comment by samueleresca** [comment]
The issue is reproducible using with the [following project](https://github.com/samueleresca/SampleAPIDockerError)
and by building the project using the following azure pipeline job [in this way.](https://dev.azure.com/samueleresca0753/SampleAPI/_build/results?buildId=1543&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b&lineStart=49&lineEnd=50&colStart=1&colEnd=1)

**Comment by joshlang** [comment]
Seems to be fixed.
