### ISSUE TITLE
Upgrade Service Fabric SDK to 4.0.457

### ISSUE THREAD

**Issue by OlegKarasik** [microsoft/azure-pipelines-image-generation#1427]
Currently you cannot execute unit-tests which use classes from latest Service Fabric SDK (4.0.457) because of the following exception:

```
Error Message:
   System.IO.FileNotFoundException : Could not load file or assembly 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\NS_7\Microsoft.ServiceFabric.Data.Impl.dll'. The system cannot find the path specified.
  Stack Trace:
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ServiceFabric.Data.ReliableStateManager..ctor(StatefulServiceContext serviceContext, ReliableStateManagerConfiguration configuration)
```

**Image impacted**
VS 2019 + Windows Server 2019

**Workaround**
It is possible to use containerized build and external image for Linux (if using Linux is an option).

Here is a YAML snippet:

``` yaml
pool:
  vmImage: 'ubuntu-16.04'

container: coherentsolutions/service-fabric-run-tests:7.0.457.1-2.2
```

**Comment by kaylangan** [comment]
This has been updated.
