### ISSUE TITLE
Initialize containers fails with "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by bgrainger** [microsoft/azure-pipelines-image-generation#1432]
This build at 7:17am (https://dev.azure.com/mysqlnet/AdoNetApiTest/_build/results?buildId=686) succeeded. The next build at 8:53am (https://dev.azure.com/mysqlnet/AdoNetApiTest/_build/results?buildId=692) failed in the "Initialize containers" step with `##[error]Object reference not set to an instance of an object.`

The primary difference I can see is in the Hosted Agent configuration. (I don't think it's related to my code because the code hasn't even been checked out yet when the failure occurs, and the azure-pipelines.yaml hasn't changed.)

**Working build:**

```
Agent name: 'Azure Pipelines 6'
Agent machine name: 'fv-az644'
Current agent version: '2.160.1'
Current image version: '20191025.1'
```

**Failing build:**

```
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az606'
Current agent version: '2.161.1'
Current image version: '20191025.1'
```

**Comment by bgrainger** [comment]
The build failed (with the same error) with both

```
    pool:
      vmimage: 'ubuntu-16.04'
```

and

```
    pool:
      vmimage: 'ubuntu-18.04'
```

**Comment by bgrainger** [comment]
Not sure if this is possibly related to https://github.com/microsoft/azure-pipelines-agent/issues/2613.

**Comment by bgrainger** [comment]
Output when enabling system diagnostics:

https://dev.azure.com/mysqlnet/AdoNetApiTest/_build/results?buildId=696

```
Status: Downloaded newer image for mysql:5.7.28
docker.io/library/mysql:5.7.28
##[error]Object reference not set to an instance of an object.
##[debug]System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Worker.Container.DockerCommandManager.DockerNetworkCreate(IExecutionContext context, String network)
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.CreateContainerNetworkAsync(IExecutionContext executionContext, String network)
   at Microsoft.VisualStudio.Services.Agent.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[section]Finishing: Initialize containers
```

**Comment by bgrainger** [comment]
I manually started a build just now and the "Initialize containers" step succeeded.

The agent version appears to have been reverted according to "Initialize job" output:

```
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az767'
Current agent version: '2.160.1'
Current image version: '20191025.1'
```

If this was a deliberate rollback to fix this issue, thank you!
