### ISSUE TITLE
npm ci no longer working on Ubuntu image 16.0.4?

### ISSUE THREAD

**Issue by phil-lgr** [Microsoft/azure-pipelines-image-generation#508]
## Description

Between November 27 and December 1th something happened on Azure Pipelines.. npm ci command stopped working:

![image](https://user-images.githubusercontent.com/9644867/49330256-1308b680-f55a-11e8-92d3-b8ef74adb84c.png)

```
2018-12-01T15:32:56.8141240Z ##[section]Starting: npm install (ci)
2018-12-01T15:32:56.8144366Z ==============================================================================
2018-12-01T15:32:56.8144454Z Task         : Command Line
2018-12-01T15:32:56.8144557Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2018-12-01T15:32:56.8144625Z Version      : 2.142.2
2018-12-01T15:32:56.8144718Z Author       : Microsoft Corporation
2018-12-01T15:32:56.8144784Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2018-12-01T15:32:56.8144892Z ==============================================================================
2018-12-01T15:32:58.2843385Z Generating script.
2018-12-01T15:32:58.2862031Z Script contents:
2018-12-01T15:32:58.2862327Z npm ci
2018-12-01T15:32:58.2890521Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/b9471da5-2a5e-450c-9fc8-f2c1e1bd7849.sh
2018-12-01T15:33:15.6605535Z /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:61
2018-12-01T15:33:15.6606545Z         fn = function () { throw arg; };
2018-12-01T15:33:15.6606805Z                            ^
2018-12-01T15:33:15.6607053Z 
2018-12-01T15:33:15.6607284Z Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
2018-12-01T15:33:15.6607507Z     at process.target.send (internal/child_process.js:578:16)
2018-12-01T15:33:15.6608314Z     at callback (/usr/local/lib/node_modules/npm/node_modules/worker-farm/lib/child/index.js:32:17)
2018-12-01T15:33:15.6608655Z     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2018-12-01T15:33:15.6608966Z     at Promise.successAdapter [as _fulfillmentHandler0] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeify.js:22:30)
2018-12-01T15:33:15.6609306Z     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
2018-12-01T15:33:15.6609569Z     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2018-12-01T15:33:15.6609872Z     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2018-12-01T15:33:15.6610125Z     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
2018-12-01T15:33:15.6610414Z     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
2018-12-01T15:33:15.6611316Z     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2018-12-01T15:33:15.6611670Z     at runCallback (timers.js:810:20)
2018-12-01T15:33:15.6611904Z     at tryOnImmediate (timers.js:768:5)
2018-12-01T15:33:15.6612166Z     at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-12-01T15:33:15.6649253Z /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:61
2018-12-01T15:33:15.6649692Z         fn = function () { throw arg; };
2018-12-01T15:33:15.6649809Z                            ^
2018-12-01T15:33:15.6649897Z 
2018-12-01T15:33:15.6650041Z Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
2018-12-01T15:33:15.6650108Z     at process.target.send (internal/child_process.js:578:16)
2018-12-01T15:33:15.6650595Z     at callback (/usr/local/lib/node_modules/npm/node_modules/worker-farm/lib/child/index.js:32:17)
2018-12-01T15:33:15.6650890Z     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2018-12-01T15:33:15.6650988Z     at Promise.successAdapter [as _fulfillmentHandler0] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeify.js:22:30)
2018-12-01T15:33:15.6651281Z     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
2018-12-01T15:33:15.6651366Z     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2018-12-01T15:33:15.6651489Z     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2018-12-01T15:33:15.6651671Z     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
2018-12-01T15:33:15.6651789Z     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
2018-12-01T15:33:15.6651875Z     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2018-12-01T15:33:15.6651983Z     at runCallback (timers.js:810:20)
2018-12-01T15:33:15.6652040Z     at tryOnImmediate (timers.js:768:5)
2018-12-01T15:33:15.6652143Z     at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-12-01T15:33:15.6856312Z ##[error]Bash exited with code '1'.
2018-12-01T15:33:15.6941421Z ##[section]Finishing: npm install (ci)
```

## Expected Behavior

I don't know what has changed between nov 27 and now... but I expect that I can see what has changed in the build agent..

the lastest image description: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md shows NodeJS 10.13.x

but we still have NodeJS 8.12.0 in Azure Pipelines 

## Actual Behavior

I'm clueless on why a build that was passing last month is now failing at the exact same commit

**Comment by phil-lgr** [comment]
Well I removed packages, put them back again and the error went away... no clue on what happened.

**Comment by dakale** [comment]
Hi Phil, glad its working again for you. Can you explain what you mean by 

> removed packages, put them back again

It may help understand what the issue was. Since you are using hosted, there is no state saved on the machine between runs so Im not sure what packages could be removed.

**Comment by phil-lgr** [comment]
I deleted every packages from my package.json and then added them progressively to see if the `npm ci` would pass.

I ended up adding everything again... and it finally passed..
