### ISSUE TITLE
Selenium WebDriver Version

### ISSUE THREAD

**Issue by MatthewSteeples** [Microsoft/azure-pipelines-image-generation#628]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: Selenium WebDrivers
- Add or update? Update
- Desired version: ChromeDriver 2.45, etc

## Areas and ecosystems
#83, @kaadhina, @lokesh755 

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [X] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [X] Windows

Due to the way that this is currently configured (downloaded from https://seleniumwebdrivers.blob.core.windows.net/seleniumwebdrivers/SeleniumWebDrivers.zip) it's not possible for us to submit pull requests. If no one has any objections then I'd be interested in getting it working using `Choco` as some other tools do

**Comment by MatthewSteeples** [comment]
Just realised that #598 may be related

**Comment by edupuis-incomm** [comment]
Hello all, it sure would be great if we could update the Hosted VS2017 agent with Selenium Web Drivers 3.141.0 and Google Chrome 72.0.3626.119 or newer. Many people have noted concerns about the agents running older version and limiting their testing. Examples:

https://developercommunity.visualstudio.com/content/problem/408469/selenium-tests-fail-due-to-old-google-chrome-versi.html
https://developercommunity.visualstudio.com/content/problem/425201/selenium-test-fail-due-to-session-not-created-for.html
https://developercommunity.visualstudio.com/content/problem/393669/unable-to-run-seleniumcodeduimstest-project-on-azu.html
https://developercommunity.visualstudio.com/content/problem/426488/selenium-webdriver-chromedriver-2450-not-running-o.html

**Comment by MatthewSteeples** [comment]
We noticed yesterday that the ChromeDriver version has updated from 2.40 to 2.45. Still not the latest but it's a step in the right direction :)

**Comment by edupuis-incomm** [comment]
Thanks for the info. I just looked this morning and it didn't appear to have changed, but I am apparently looking at the wrong place. 

![image](https://user-images.githubusercontent.com/34722540/53430030-f211ff00-39aa-11e9-8dba-a271947d3b2d.png)

**Comment by MatthewSteeples** [comment]
Yeah, this is where half the problem with how this task is implemented surfaces. When Selenium is "installed" on the build server, all it does is download and extract the zip file from the blob storage url referenced in my first post. So it would appear that someone has updated that zip file, but not the docs (I'm not reading the version number from the docs, I'm reading it from the logs of our builds).

**Comment by kaylangan** [comment]
Related to #861

**Comment by MatthewSteeples** [comment]
Just to flag this, this is causing us a problem currently until the versions catch up:

Since 2nd July our builds have been failing because ChromeDriver was updated to the latest version in the image, but Chrome hasn't been (as far as we can tell). This means we either have to build our own image or disable our tests until the latest image properly rolls out (2-3 weeks).

**Comment by kaadhina** [comment]
Hi, we updated the versions to latest available at the time of updating. And these versions were documented to be supported ones. Can you please share more details about the issues you are facing (debug logs might help)
And as a workaround, you may try using you own copy of driver versions instead of the ones baked in the image (or replace the ones on the hosted with an xcopy)

**Comment by MatthewSteeples** [comment]
@kaadhina The problem is that the way that this has been updated (via the Storage Account) means it doesn't roll out alongside the build image, but is also applied to all older images too. This means that the version of ChromeDriver is now newer than the version of Chrome on the VM (I think).

We've been seeing 2 different errors (depending on which version of Selenium we're using).

**Selenium 4 Alpha**
>Initialization method Ledgerscope.AutomationTests.Selenium.Tests.CheckMyBooks.BalanceSheetTests.SetupForEveryTestMethod threw exception. OpenQA.Selenium.WebDriverException: invalid session id.
TestCleanup method Ledgerscope.AutomationTests.Selenium.Tests.CheckMyBooks.BalanceSheetTests.CleanUpAfterEveryTestMethod threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: invalid session id.
>     at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
>   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
>   at OpenQA.Selenium.Remote.RemoteNavigator.GoToUrl(String url)

**Selenium 3.141**
>TestCleanup method Ledgerscope.AutomationTests.Selenium.Tests.SystemTests.CleanUpAfterEveryTestMethod threw exception. System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object..
>at OpenQA.Selenium.Remote.HttpCommandExecutor.HttpRequestInfo..ctor(Uri serverUri, Command commandToExecute, CommandInfo commandInfo)
>   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
>   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
>   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>   at OpenQA.Selenium.Remote.RemoteLogs.GetLog(String logKind)

Our agents still show the version from the last sprint
> 2019-07-10T13:27:13.4629462Z Current agent version: '2.153.2'

**Comment by kaadhina** [comment]
Hi, I just checked the versions and it looks like both the browser and driver are at 75.
the update process is alongside the build image. Is it at image generation time that the versions from the storage are pulled down, so it will not affect any image (including older ones) that have already been created/built.

**Comment by MatthewSteeples** [comment]
> Is it at image generation time that the versions from the storage are pulled down, so it will not affect any image (including older ones) that have already been created/built

It _does_ affect earlier images. We're on 2.153.2 and have had ChromeDriver 75 since 2nd July at 17:02 UTC. Prior to that (same day, 15:09 UTC), we were on image 2.153.2 (the **exact same number**) and had ChromeDriver 74. We made no changes to our definition during that time.

I'm more than happy to grant you access to our subscription so you can see this for yourself. We're using the built in images, not installing any extras, and using ChromeDriver that is exposed through the environment variable

Look at the stats for the blob storage account that the WebDrivers are hosted on. How many times per day are they downloaded?

**Comment by kaadhina** [comment]
Hi, the agent version is not related to the image version. These two follow two completely different deployment processes and schedules.

**Comment by MatthewSteeples** [comment]
@kaadhina Well that explains a few things :$

I managed to confirm what you were saying by getting a script to run `Get-WmiObject win32_product` on the build machine and it's reporting Chrome 75 is installed so our issue must be unrelated to this then. Thanks for pointing these things out to me.
